### ISSUE TITLE
Provide set of URLs as an input file

### ISSUE THREAD

**Issue by witsch** [hatoo/oha#250]
It'd be very useful to use a set of given URLs for the load test, much like [siege's "URL file"](https://www.joedog.org/siege-manual/#a05):

> In order to run a regression test or an effective internet simulation, you are going to have to run through the URLs on the server you are testing. To accomplish that, place the URLs in a configuration file.

This makes it possible to collect a realistic set of URL, i.e. from an access log etc, and "replay" them in order to test or ensure performance requirements are still met after some changes.

**Comment by wjhoward** [comment]
I would suggest extending this idea by providing the ability to set request headers too. Maybe this could be configured by an input YAML file, e.g:
```yaml
- name: test_one
  path: /test_path
  headers:
    host: test
    user-agent: test_user_agent

- name: test_two
...     
```

These test cases could be cycled through in order. A possible later development could be to provide a test case weighting percentage.
